const assert=require('node:assert/strict'),fs=require('node:fs'),{JSDOM}=require('jsdom');
const dom=new JSDOM(fs.readFileSync('app/static/panel-nuevo-diseno.html','utf8'),{url:'https://panel.test/admin',runScripts:'outside-only'}),w=dom.window,d=w.document;
w.eval(fs.readFileSync('app/static/bot-cost-analytics.js','utf8'));
const base={costo_usd:.0366,eventos:2,llamadas_ia:1,mensajes:1,tokens:11000,cache_read:3000,cache_write:5000,segundos_audio:60,sin_precio:1,errores:0,entregados:1,conversaciones_ia:1,promedio_por_chat:.0366,latencia_media_ms:1200};
const data={desde:'2026-10-01',hasta:'2026-10-08',totales:base,anterior:{...base,desde:'2026-09-23',hasta:'2026-09-30',costo_usd:0},serie:[{...base,fecha:'2026-10-01'},{...base,costo_usd:0,eventos:0,fecha:'2026-10-02'}],proveedores:[{...base,nombre:'anthropic'}],funciones:[{...base,nombre:'respuesta_automatica'}],modelos:[{...base,nombre:'claude-sonnet-5'}],chats:[{...base,nombre:'<img src=x onerror=alert(1)>'}],horas:Array(24).fill(0),dias_semana:[0,1,0,0,0,0,0],picos:{dia:{...base,fecha:'2026-10-01'},mes:{...base,fecha:'2026-10'},ano:{...base,fecha:'2026'}},gastos_confirmados:[{id:1,proveedor:'servidor',concepto:'Hosting',referencia:'INV-1',fecha:'2026-10-01',monto_usd:12,archivado:false}],total_confirmado:12,historicos_sin_desglose:1,seguimiento_detallado_desde:'2026-10-01T05:00:00Z'};
const tick=()=>new Promise(r=>setImmediate(r));let requests=[],posts=[],defer=null,mode='ok';
const get=async url=>{requests.push(url);if(defer){const p=defer;defer=null;return p}return{ok:mode==='ok',json:async()=>mode==='ok'?data:{detail:'Período inválido'}}};
let resolvePost;
const post=async(url,body)=>{posts.push({url,body});if(resolvePost===true)return new Promise(r=>resolvePost=r);return{ok:true,json:async()=>({id:1})}};
(async()=>{w.BotCosts.init(get,post);await w.BotCosts.load();assert.match(d.getElementById('bc-kpis').textContent,/0.0366/);assert.match(d.getElementById('bc-kpis').textContent,/12.0000/);assert.match(d.getElementById('bc-coverage').textContent,/1 eventos sin precio/);assert.equal(d.querySelectorAll('#bc-chart rect').length,2);assert.equal(d.querySelectorAll('#bc-series tbody tr').length,2);assert.equal(d.querySelector('#bc-chats img'),null);assert.equal(d.querySelectorAll('#bc-hours .bc-bars>div').length,24);assert.equal(d.querySelectorAll('#bc-peaks article').length,3);
 d.getElementById('bc-provider').value='openai';d.getElementById('bc-provider').dispatchEvent(new w.Event('change'));await tick();assert.match(requests.at(-1),/proveedor=openai/);d.getElementById('bc-group').value='ano';d.getElementById('bc-group').dispatchEvent(new w.Event('change'));await tick();assert.match(requests.at(-1),/agrupacion=ano/);
 // A slow earlier request must not replace a newer result.
 let release;defer=new Promise(r=>release=r);const slow=w.BotCosts.load();await w.BotCosts.load();release({ok:true,json:async()=>({...data,totales:{...base,costo_usd:999}})});await slow;assert.doesNotMatch(d.getElementById('bc-kpis').textContent,/999/);
 d.getElementById('bc-expenses').querySelector('button').click();await tick();assert.equal(posts.at(-1).body.accion,'archivar');
 const form=d.getElementById('bc-exp-form');d.getElementById('bc-concept').value='API';d.getElementById('bc-amount').value='12.50';resolvePost=true;form.dispatchEvent(new w.Event('submit',{cancelable:true}));form.dispatchEvent(new w.Event('submit',{cancelable:true}));assert.equal(posts.filter(x=>x.url==='/panel/costos/gastos').length,1);assert.equal(d.getElementById('bc-save').disabled,true);resolvePost({ok:true});await tick();await tick();assert.equal(d.getElementById('bc-save').disabled,false);assert.match(d.getElementById('bc-save-status').textContent,/Gasto guardado/);
 mode='error';await w.BotCosts.load();assert.match(d.getElementById('bc-status').textContent,/Período inválido/);assert.equal(d.getElementById('bc-export').disabled,true);
 console.log('Cost analytics UI: filters, estimates, unknown costs, charts, XSS, stale requests, archive and duplicate guards passed');dom.window.close();})().catch(e=>{console.error(e);dom.window.close();process.exitCode=1});
